name: Unzip File on Push

on: 
  push:
    branches:
      - main  # Change to your branch if different

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip File
        run: unzip your-folder.zip -d extracted-files  # Change "your-folder.zip" to your actual ZIP filename

      - name: Commit Extracted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add extracted-files
          git commit -m "Unzipped files"
          git push
