name: Unzip File on Push

on: 
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List All Files in the Repo
        run: ls -R

      - name: Find ZIP File
        run: |
          ZIP_FILE=$(find . -name "tesseract-landing.zip")
          echo "Found ZIP file: $ZIP_FILE"
          test -f "$ZIP_FILE" || echo "ZIP file not found!"

      - name: Create directory for extracted files
        run: mkdir -p extracted-files

      - name: Unzip File
        run: unzip -o $(find . -name 'tesseract-landing.zip') -d extracted-files

      - name: List Extracted Files
        run: ls -lah extracted-files || echo "No extracted files found"

      - name: Commit Extracted Files
        run: |
          git config --global user.name "smilt10"
          git config --global user.email "gideon.owusu3057@gmail.com"
          git add extracted-files/* || echo "No files to add"
          echo "Files staged for commit:"
          git status
          git commit -m "Unzipped files" || echo "No changes to commit"
          git push || echo "Push failed"
        continue-on-error: true
